version: "3.7"
services:
  auth-service:
    image: d2-core/prototype-auth-service:1.0.0
    ports:
      - "8080:8080"
    networks:
      - prototype
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
  event-service:
    image: d2-core/prototype-event-service:1.0.0
    ports:
      - "8081:8080"
    networks:
      - prototype
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
  notification-service:
    image: d2-core/prototype-notification-service:1.0.0
    ports:
      - "8082:8080"
    networks:
      - prototype
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
  product-service:
    image: d2-core/prototype-product-service:1.0.0
    ports:
      - "8083:8080"
    networks:
      - prototype
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
  prototype-bff-app:
    image: d2-core/prototype-bff-app:1.0.0
    ports:
      - "3000:3000"
    networks:
      - prototype
  prototype-bff-admin:
    image: d2-core/prototype-bff-admin:1.0.0
    ports:
      - "3001:3000"
    networks:
      - prototype

networks:
  prototype:
    external: true
