version: "3.7"
services:
  auth-service:
    image: d2-core/prototype-auth-service:1.0.0
    ports:
      - "8080:8080"
    networks:
      - prototype
    environment:
      - SPRING_PROFILES_ACTIVE=local
  event-service:
    image: d2-core/prototype-event-service:1.0.0
    ports:
      - "8081:8080"
    networks:
      - prototype
    environment:
      - SPRING_PROFILES_ACTIVE=local
  notification-service:
    image: d2-core/prototype-notification-service:1.0.0
    ports:
      - "8082:8080"
    networks:
      - prototype
    environment:
      - SPRING_PROFILES_ACTIVE=local
  product-service:
    image: d2-core/prototype-product-service:1.0.0
    ports:
      - "8083:8080"
    networks:
      - prototype
    environment:
      - SPRING_PROFILES_ACTIVE=local

networks:
  prototype:
    external: true
